const fs = require('fs');
const path = require('path');

const summariesDir = path.join(__dirname, '..', 'final', 'summaries');
const outputPath = path.join(__dirname, '..', 'prototype', 'react', 'docsData.js');

const files = fs.readdirSync(summariesDir).filter(f => f.endsWith('.md')).sort();

const escapeContent = (str) =>
  str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');

const extractTitle = (content, fallback) => {
  const lines = content.split(/\r?\n/);
  for (const line of lines) {
    if (line.startsWith('# ')) {
      return line.replace(/^#\s*/, '').trim();
    }
  }
  return fallback;
};

const extractLinks = (content) => {
  const linkRegex = /\[[^\]]+\]\(([^)]+)\)/g;
  const targets = new Set();
  let match;
  while ((match = linkRegex.exec(content)) !== null) {
    const target = match[1];
    if (!target.includes('://') && !target.includes('/')) {
      targets.add(target.trim());
    }
  }
  return Array.from(targets);
};

const docs = {};

for (const file of files) {
  const base = path.basename(file, '.md');
  const fullPath = path.join(summariesDir, file);
  const raw = fs.readFileSync(fullPath, 'utf8');
  const title = extractTitle(raw, base);
  docs[base] = {
    id: base,
    title,
    filename: file,
    links: extractLinks(raw),
    content: escapeContent(raw)
  };
}

const preferredStartOrder = [
  'ExecutionPlan',
  'MasterIssueChecklist',
];
let startId = Object.keys(docs)[0];
for (const id of preferredStartOrder) {
  if (docs[id]) {
    startId = id;
    break;
  }
}

const output = `// Auto-generated by scripts/generateDocsData.js\n` +
`export const DOCS = {\n` +
Object.entries(docs)
  .map(([id, doc]) => `  "${id}": {\n    id: "${doc.id}",\n    title: \`${doc.title}\`,\n    filename: "${doc.filename}",\n    links: ${JSON.stringify(doc.links)},\n    content: \`${doc.content}\`\n  }`)
  .join(',\n') +
`\n};\n\nexport const DOC_IDS = Object.keys(DOCS);\nexport const START_DOC_ID = "${startId}";\n`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output, 'utf8');
console.log(`Wrote ${Object.keys(docs).length} docs to ${outputPath}`);
